repos:

- repo: https://github.com/commitizen-tools/commitizen
  rev: v1.17.0
  hooks:
    - id: commitizen
      stages: [commit-msg]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
    - id: actionlint

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

-  repo: https://github.com/jorisroovers/gitlint
   rev: v0.19.1
   hooks:
   -   id: gitlint

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-illegal-windows-names
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: destroyed-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: ["--autofix"]

- repo: https://github.com/crate-ci/typos
  rev: v1.31.0
  hooks:
    - id: typos

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.398
  hooks:
    - id: pyright
